/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BurgerService } from "../burger.service";
import { BurgerCreateInput } from "./BurgerCreateInput";
import { Burger } from "./Burger";
import { BurgerFindManyArgs } from "./BurgerFindManyArgs";
import { BurgerWhereUniqueInput } from "./BurgerWhereUniqueInput";
import { BurgerUpdateInput } from "./BurgerUpdateInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";

export class BurgerControllerBase {
  constructor(protected readonly service: BurgerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Burger })
  async createBurger(@common.Body() data: BurgerCreateInput): Promise<Burger> {
    return await this.service.createBurger({
      data: data,
      select: {
        createdAt: true,
        id: true,
        ingredients: true,
        name: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Burger] })
  @ApiNestedQuery(BurgerFindManyArgs)
  async burgers(@common.Req() request: Request): Promise<Burger[]> {
    const args = plainToClass(BurgerFindManyArgs, request.query);
    return this.service.burgers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        ingredients: true,
        name: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Burger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async burger(
    @common.Param() params: BurgerWhereUniqueInput
  ): Promise<Burger | null> {
    const result = await this.service.burger({
      where: params,
      select: {
        createdAt: true,
        id: true,
        ingredients: true,
        name: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Burger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBurger(
    @common.Param() params: BurgerWhereUniqueInput,
    @common.Body() data: BurgerUpdateInput
  ): Promise<Burger | null> {
    try {
      return await this.service.updateBurger({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          ingredients: true,
          name: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Burger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBurger(
    @common.Param() params: BurgerWhereUniqueInput
  ): Promise<Burger | null> {
    try {
      return await this.service.deleteBurger({
        where: params,
        select: {
          createdAt: true,
          id: true,
          ingredients: true,
          name: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/orders")
  @ApiNestedQuery(OrderFindManyArgs)
  async findOrders(
    @common.Req() request: Request,
    @common.Param() params: BurgerWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findOrders(params.id, {
      ...query,
      select: {
        burger: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        delivery: {
          select: {
            id: true,
          },
        },

        id: true,
        orderDate: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orders")
  async connectOrders(
    @common.Param() params: BurgerWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        connect: body,
      },
    };
    await this.service.updateBurger({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orders")
  async updateOrders(
    @common.Param() params: BurgerWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        set: body,
      },
    };
    await this.service.updateBurger({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orders")
  async disconnectOrders(
    @common.Param() params: BurgerWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        disconnect: body,
      },
    };
    await this.service.updateBurger({
      where: params,
      data,
      select: { id: true },
    });
  }
}
